from . import stock_receipt
from . import stock_receipt_card
from . import stock_picking
from . import stock_move
from . import stock_quant
from . import stock_lot
from . import stock_action_wizard
from . import product_card_list_2tab
from . import stock_card_form
from . import stock_card_line
from . import product_type
from . import product_template
from . import product_creation_wizard