{
    'name': 'T4Tek Tracking Odoo 18.0',
    'version': '1.0',
    "author": "Đặng Thành Nhân",
    'sequence': 0,
    'description': '',
    'depends': [ "stock", "product", "web", "bus", "base", "rfid_reader"],
    'installable': True,
    'auto_install': True,
    'application': True,
    'data':
        [
        'security/access_user.xml',
        'security/ir.model.access.csv',
        "data/product_card_list_2tab.xml",
        "data/product_card_list_2tab2.xml",
        "data/product_card_list_2tab3.xml",
        "data/cron_jobs.xml",
        'data/product_type_data.xml',
        "views/stock_receipt_views.xml",
        'views/product_template.xml',   
        "views/stock_picking_view.xml",
        "views/stock_move_line_view.xml",
        "views/list_multitab_view.xml",
        "views/stock_action_wizard_view.xml",
        "views/stock_receipt_card_view.xml",
        'views/stock_card_form_view.xml',
        'views/product_type_view.xml',
        'views/product_creation_wizard.xml',
        "views/menu_views.xml",
    ],
    'assets': {
         'web.assets_backend': [
            't4tek_device_tracking/static/src/js/share/**/*',
            't4tek_device_tracking/static/src/xml/share/**/*',
            't4tek_device_tracking/static/src/js/backend/**/*',
            't4tek_device_tracking/static/src/css/backend/**/*',
            't4tek_device_tracking/static/src/xml/backend/**/*',
            't4tek_device_tracking/static/images/**/*',
            't4tek_device_tracking/static/audio/*.wav',
            
        ],
    },
    'license': 'LGPL-3',
}
